#server:
#  port: 11080

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    com: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


############General Setting##############
setting:
  browser: Chrome
  screenshot-folder: test-result/
  isHeadless: false
  timeInterval: 0
############/General Setting##############


############Search Test Setting##############
search:
  googlePage: http://google.com/
  yahooPage: http://yahoo.co.jp/
  naverPage: http://naver.com/
############/Search Test Setting##############


############Ajax Test Setting##############
ajax:
  ajaxPage: http://localhost:11080/top
  time: 4
############/Ajax Test Setting##############

