server:
  port: 11080

setting:
  browser: Chrome
  screenshot-folder: test-result/
  isHeadless: true
  timeInterval: 1

search:
  googlePage: http://google.co.jp/
  yahooPage: http://yahoo.co.jp/
  naverPage: http://naver.com/

ajax:
  examplePage1: http://localhost:11080/time/top
  time: 3