setting:
  browser: Chrome
  screenshot-folder: test-result/
  isHeadless: true
  timeInterval: 1

search:
  googlePage: http://google.com/
  yahooPage: http://yahoo.co.jp/
  naverPage: http://naver.com/

ajax:
  examplePage1: https://codepen.io/btholt/pen/FArdh
  examplePage2: http://localhost:11080/time/top